% Define images to process
imageFileNames = {'C:\Users\applegoodeat\Desktop\Image351.png',...
    'C:\Users\applegoodeat\Desktop\Image128.png',...
    'C:\Users\applegoodeat\Desktop\Image144.png',...
    'C:\Users\applegoodeat\Desktop\Image162.png',...
    'C:\Users\applegoodeat\Desktop\Image172.png',...
    'C:\Users\applegoodeat\Desktop\Image272.png',...
    'C:\Users\applegoodeat\Desktop\Image278.png',...
    'C:\Users\applegoodeat\Desktop\Image297.png',...
    'C:\Users\applegoodeat\Desktop\Image027.png',...
    'C:\Users\applegoodeat\Desktop\Image181.png',...
    'C:\Users\applegoodeat\Desktop\Image194.png',...
    'C:\Users\applegoodeat\Desktop\Image317.png',...
    'C:\Users\applegoodeat\Desktop\Image231.png',...
    'C:\Users\applegoodeat\Desktop\Image055.png',...
    'C:\Users\applegoodeat\Desktop\Image241.png',...
    'C:\Users\applegoodeat\Desktop\Image318.png',...
    'C:\Users\applegoodeat\Desktop\Image082.png',...
    'C:\Users\applegoodeat\Desktop\Image245.png',...
    'C:\Users\applegoodeat\Desktop\Image328.png',...
    'C:\Users\applegoodeat\Desktop\Image089.png',...
    };
% Detect calibration pattern in images
detector = vision.calibration.monocular.CheckerboardDetector();
[imagePoints, imagesUsed] = detectPatternPoints(detector, imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Read the first image to obtain image size
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates for the planar pattern keypoints
squareSize = 19;  % in units of 'millimeters'
worldPoints = generateWorldPoints(detector, 'SquareSize', squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
h1=figure; showReprojectionErrors(cameraParams);

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParams);

% For example, you can use the calibration data to remove effects of lens distortion.
undistortedImage = undistortImage(originalImage, cameraParams);


% save Intrinsics 
intrinsics = cameraParams.Intrinsics;
save('myIntrinsics.mat', 'intrinsics');


